/**
 * Composite "theme packs". Each pack applies a curated set of CSS variables at
 * once, giving users one-click access to opinionated looks like comic, neon,
 * glass, etc. Picking a pack overwrites only the variables it specifies — any
 * other tweaks the user has already made are preserved.
 */

export interface ThemePack {
  id: string;
  label: string;
  /** Short tagline used in the picker card. */
  description: string;
  /** Tiny preview swatches, two colours for a gradient pill. */
  swatch: [string, string];
  vars: Record<string, string>;
}

export const THEME_PACKS: ThemePack[] = [
  {
    id: 'overlay-default',
    label: 'Overlay default',
    description: 'Transparent overlay with a soft text outline. Matches the base look.',
    swatch: ['#1d2540', '#0c1224'],
    vars: {
      '--co-font': "'Inter', system-ui, sans-serif",
      '--co-font-size': '20px',
      '--co-font-weight': '400',
      '--co-letter-spacing': 'normal',
      '--co-text': '#ffffff',
      '--co-text-shadow': '0 0 2px #000, 0 0 4px #000, 1px 1px 2px #000',
      '--co-username-weight': '700',
      '--co-username-transform': 'none',
      '--co-username-letter-spacing': 'normal',
      '--co-card-bg': 'transparent',
      '--co-card-border': '0 solid transparent',
      '--co-card-shadow': 'none',
      '--co-card-backdrop': 'none',
      '--co-card-max-width': '100%',
      '--co-radius': '6px',
      '--co-padding': '6px 10px',
      '--co-message-gap': '6px',
      '--co-reply-opacity': '0.75',
      '--co-reply-style': 'normal',
      '--co-reply-color': 'inherit',
      '--co-enter-translate': '6px',
      '--co-enter-easing': 'ease-out',
    },
  },
  {
    id: 'glass',
    label: 'Glass card',
    description: 'Frosted translucent card with a soft drop shadow. Great over busy gameplay.',
    swatch: ['#5b6f9a', '#1d2540'],
    vars: {
      '--co-font': "'Inter', system-ui, sans-serif",
      '--co-font-size': '20px',
      '--co-font-weight': '500',
      '--co-text': '#f8fbff',
      '--co-text-shadow': '0 1px 0 rgba(0,0,0,0.55), 0 2px 6px rgba(0,0,0,0.85)',
      '--co-card-bg': 'linear-gradient(180deg, rgba(25, 34, 58, 0.72), rgba(14, 20, 36, 0.66))',
      '--co-card-border': '1px solid rgba(194,219,255,0.16)',
      '--co-card-shadow': 'inset 0 1px 0 rgba(255,255,255,0.07), 0 10px 24px rgba(0,0,0,0.28)',
      '--co-card-backdrop': 'blur(12px) saturate(120%)',
      '--co-card-max-width': 'min(92%, 760px)',
      '--co-radius': '14px',
      '--co-padding': '10px 14px',
      '--co-message-gap': '10px',
    },
  },
  {
    id: 'sleek-futurist',
    label: 'Sleek futurist',
    description: 'Sharp edges, low-emission neon, mono-influenced display font.',
    swatch: ['#00e5ff', '#0a1a2a'],
    vars: {
      '--co-font': "'Orbitron', system-ui, sans-serif",
      '--co-font-size': '20px',
      '--co-font-weight': '500',
      '--co-letter-spacing': '0.04em',
      '--co-text': '#dffaff',
      '--co-text-shadow': '0 0 6px rgba(0, 229, 255, 0.55)',
      '--co-username-weight': '700',
      '--co-username-letter-spacing': '0.08em',
      '--co-username-transform': 'uppercase',
      '--co-card-bg': 'linear-gradient(180deg, rgba(8,18,32,0.85), rgba(4,8,16,0.85))',
      '--co-card-border': '1px solid rgba(0,229,255,0.6)',
      '--co-card-shadow': '0 0 14px rgba(0,229,255,0.35)',
      '--co-card-backdrop': 'blur(6px)',
      '--co-card-max-width': 'min(92%, 720px)',
      '--co-radius': '4px',
      '--co-padding': '8px 12px',
      '--co-message-gap': '8px',
      '--co-enter-easing': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    },
  },
  {
    id: 'neon-arcade',
    label: 'Neon arcade',
    description: 'Magenta/cyan glow, pixel-display username, perfect for retro streams.',
    swatch: ['#ff3df0', '#00e5ff'],
    vars: {
      '--co-font': "'Press Start 2P', ui-monospace, monospace",
      '--co-font-size': '15px',
      '--co-line-height': '1.6',
      '--co-text': '#ffffff',
      '--co-text-shadow': '0 0 6px #ff3df0, 0 0 14px #ff3df0',
      '--co-username-weight': '400',
      '--co-username-transform': 'uppercase',
      '--co-card-bg': 'rgba(10, 5, 25, 0.7)',
      '--co-card-border': '2px solid #ff3df0',
      '--co-card-shadow': '0 0 14px rgba(0,229,255,0.55), 0 0 28px rgba(255,61,240,0.35)',
      '--co-card-max-width': 'min(92%, 700px)',
      '--co-radius': '4px',
      '--co-padding': '10px 14px',
      '--co-message-gap': '10px',
      '--co-enter-translate': '0px',
    },
  },
  {
    id: 'comic-pop',
    label: 'Comic pop',
    description: 'Heavy ink outlines, bold display font, comic-book offset shadow.',
    swatch: ['#fff3a0', '#111111'],
    vars: {
      '--co-font': "'Bangers', 'Comic Sans MS', cursive",
      '--co-font-size': '22px',
      '--co-line-height': '1.25',
      '--co-letter-spacing': '0.03em',
      '--co-text': '#111111',
      '--co-text-shadow': 'none',
      '--co-username-weight': '700',
      '--co-username-transform': 'uppercase',
      '--co-card-bg': '#fff3a0',
      '--co-card-border': '3px solid #111',
      '--co-card-shadow': '4px 4px 0 #111',
      '--co-card-backdrop': 'none',
      '--co-card-max-width': 'min(92%, 680px)',
      '--co-radius': '14px',
      '--co-padding': '8px 14px',
      '--co-message-gap': '12px',
      '--co-reply-opacity': '1',
      '--co-reply-color': '#444',
      '--co-enter-translate': '0px',
      '--co-enter-easing': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    },
  },
  {
    id: 'newspaper',
    label: 'Newspaper',
    description: 'Serif headlines on a cream card. Calm, editorial vibe.',
    swatch: ['#f7eedd', '#1c1a14'],
    vars: {
      '--co-font': "'Merriweather', Georgia, serif",
      '--co-font-size': '19px',
      '--co-line-height': '1.5',
      '--co-text': '#1c1a14',
      '--co-text-shadow': 'none',
      '--co-username-weight': '900',
      '--co-username-letter-spacing': '0.02em',
      '--co-card-bg': '#f7eedd',
      '--co-card-border': '1px solid rgba(0,0,0,0.12)',
      '--co-card-shadow': '0 1px 0 rgba(0,0,0,0.05)',
      '--co-card-max-width': 'min(92%, 760px)',
      '--co-radius': '4px',
      '--co-padding': '10px 14px',
      '--co-message-gap': '8px',
      '--co-reply-style': 'italic',
      '--co-reply-color': '#5b554a',
    },
  },
  {
    id: 'hand-written',
    label: 'Hand-written',
    description: 'Casual marker handwriting on a translucent card.',
    swatch: ['#fff7c2', '#3a2a14'],
    vars: {
      '--co-font': "'Caveat', 'Comic Sans MS', cursive",
      '--co-font-size': '24px',
      '--co-line-height': '1.3',
      '--co-text': '#3a2a14',
      '--co-text-shadow': 'none',
      '--co-username-weight': '700',
      '--co-card-bg': 'rgba(255, 247, 194, 0.85)',
      '--co-card-border': '1px dashed rgba(58, 42, 20, 0.45)',
      '--co-card-shadow': '0 2px 6px rgba(0,0,0,0.18)',
      '--co-card-max-width': 'min(92%, 640px)',
      '--co-radius': '12px',
      '--co-padding': '6px 12px',
      '--co-message-gap': '6px',
    },
  },
  {
    id: 'minimal-line',
    label: 'Minimal line',
    description: 'No card. Tightly packed text, perfect for clean OBS captures.',
    swatch: ['#ffffff', '#222222'],
    vars: {
      '--co-font': "'IBM Plex Sans', system-ui, sans-serif",
      '--co-font-size': '19px',
      '--co-line-height': '1.28',
      '--co-text': '#ffffff',
      '--co-text-shadow': '0 0 2px rgba(0,0,0,0.9), 0 1px 3px rgba(0,0,0,0.75)',
      '--co-card-bg': 'transparent',
      '--co-card-border': '0 solid transparent',
      '--co-card-shadow': 'none',
      '--co-card-backdrop': 'none',
      '--co-card-max-width': '100%',
      '--co-radius': '0',
      '--co-padding': '2px 0',
      '--co-message-gap': '4px',
      '--co-enter-translate': '4px',
    },
  },
];

export function findThemePack(id: string | undefined): ThemePack | undefined {
  if (!id) return undefined;
  return THEME_PACKS.find((p) => p.id === id);
}
